subnets:
  - subnet-047817183bd31a187 
  - subnet-03c251ec1c5c0d8fd
#replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
image:
  repository: boicotaz/my-nginx
  tag: "1.0"
