apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: sqs-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: SQS_QUEUE_URL
              value: {{ .Values.aws.queueUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
