{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sqs-consumer-auth
spec:
  podIdentity:
    provider: aws
    identityOwner: keda
{{- end }}
