apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    {{- range $key, $val := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
